import { execFileSync, spawnSync } from "child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync, chownSync, statSync } from "fs";
import { dirname, join, resolve } from "path";
import { CA } from "../ca";
import { groupExists, userExists, getGroupGid } from "../groups";

const WRAPPER_PATH = "/usr/bin/mad";
const SSHD_CA_PATH = "/etc/ssh/mad_ca.pub";
const SSHD_KRL_PATH = "/etc/ssh/mad_krl";
const SSHD_SNIPPET_PATH = "/etc/ssh/sshd_config.d/99-mad.conf";
const SYSTEMD_UNIT_PATH = "/etc/systemd/system/mad-daemon.service";
const CA_KEY_PATH = "/etc/mad/ca/ca.key";

const REQUIRED_GROUPS = ["mad", "mad-users", "mad-admin"];

interface Action { changed: boolean; note: string }

function note(changed: boolean, msg: string): Action {
    return { changed, note: msg };
}

function detectInstallDir(): string {
    // process.argv[1] is the entry script (cli.ts when run via tsx, or the wrapper that exec's tsx).
    // Walk up until we find package.json.
    let dir = resolve(process.argv[1] ?? ".");
    for (let i = 0; i < 6; i++) {
        dir = dirname(dir);
        if (existsSync(join(dir, "package.json"))) return dir;
    }
    throw new Error("could not locate install dir (no package.json found above " + process.argv[1] + ")");
}

function ensureGroup(name: string): Action {
    if (groupExists(name)) return note(false, `group ${name} exists`);
    execFileSync("groupadd", [name], { stdio: "inherit" });
    return note(true, `created group ${name}`);
}

function ensureOtpUser(): Action {
    if (userExists("otp")) return note(false, "user otp exists");
    execFileSync("useradd", ["-m", "-s", "/usr/sbin/nologin", "-G", "mad", "otp"], { stdio: "inherit" });
    return note(true, "created user otp");
}

function ensureDir(path: string, mode: number, owner: { uid: number; gid: number } | undefined): Action {
    let changed = false;
    if (!existsSync(path)) {
        mkdirSync(path, { recursive: true });
        changed = true;
    }
    const s = statSync(path);
    const wantMode = mode & 0o7777;
    if ((s.mode & 0o7777) !== wantMode) {
        chmodSync(path, wantMode);
        changed = true;
    }
    if (owner && (s.uid !== owner.uid || s.gid !== owner.gid)) {
        chownSync(path, owner.uid, owner.gid);
        changed = true;
    }
    return note(changed, `${changed ? "fixed" : "ok"} dir ${path}`);
}

function ensureKrl(ca: CA): Action {
    if (existsSync(SSHD_KRL_PATH)) return note(false, `ok ${SSHD_KRL_PATH}`);
    const krl = ca.generateKrl([]);
    writeFileSync(SSHD_KRL_PATH, krl);
    chmodSync(SSHD_KRL_PATH, 0o644);
    return note(true, `wrote ${SSHD_KRL_PATH} (empty signed KRL)`);
}

function writeIfChanged(path: string, content: string, mode: number, owner?: { uid: number; gid: number }): Action {
    let changed = false;
    if (!existsSync(path) || readFileSync(path, "utf-8") !== content) {
        mkdirSync(dirname(path), { recursive: true });
        writeFileSync(path, content);
        changed = true;
    }
    const s = statSync(path);
    const wantMode = mode & 0o7777;
    if ((s.mode & 0o7777) !== wantMode) { chmodSync(path, wantMode); changed = true; }
    if (owner && (s.uid !== owner.uid || s.gid !== owner.gid)) { chownSync(path, owner.uid, owner.gid); changed = true; }
    return note(changed, `${changed ? "wrote" : "ok"} ${path}`);
}

function wrapperContent(installDir: string): string {
    return `#!/bin/bash
# Generated by 'mad setup'. Re-run setup to regenerate.
exec bun run ${installDir}/src/cli.ts "$@"
`;
}

function readSnippet(installDir: string): string {
    return readFileSync(join(installDir, "systemd/sshd_config.snippet"), "utf-8");
}

function readUnit(installDir: string): string {
    return readFileSync(join(installDir, "systemd/mad-daemon.service"), "utf-8");
}

function systemctlReload(unit: string): void {
    spawnSync("systemctl", ["reload-or-restart", unit], { stdio: "inherit" });
}

function systemctlEnableNow(unit: string): void {
    spawnSync("systemctl", ["daemon-reload"], { stdio: "inherit" });
    spawnSync("systemctl", ["enable", "--now", unit], { stdio: "inherit" });
}

function isActive(unit: string): boolean {
    return spawnSync("systemctl", ["is-active", "--quiet", unit]).status === 0;
}

export async function runSetup(): Promise<void> {
    if (process.getuid?.() !== 0)
        throw new Error("mad setup must run as root");

    const installDir = detectInstallDir();
    process.stdout.write(`install dir: ${installDir}\n\n`);

    const actions: Action[] = [];
    for (const g of REQUIRED_GROUPS) actions.push(ensureGroup(g));
    actions.push(ensureOtpUser());

    actions.push(ensureDir("/etc/mad", 0o755, undefined));
    actions.push(ensureDir("/etc/mad/ca", 0o700, undefined));
    actions.push(ensureDir("/etc/mad/groups", 0o755, undefined));
    actions.push(ensureDir("/var/lib/mad", 0o750, { uid: 0, gid: getGroupGid("mad") ?? 0 }));
    actions.push(ensureDir("/run/mad", 0o750, { uid: 0, gid: getGroupGid("mad") ?? 0 }));
    actions.push(ensureDir("/run/mad/groups", 0o755, undefined));

    // Materialize the CA (constructor creates ca.key if missing) and publish its public key.
    const ca = new CA(CA_KEY_PATH);
    actions.push(writeIfChanged(SSHD_CA_PATH, ca.publicKey() + "\n", 0o644));

    // Make sure /etc/ssh/mad_krl exists *before* we reload sshd with
    // RevokedKeys pointing at it (sshd refuses all auth if the file is set
    // but unreadable). Use an empty KRL signed by the CA — the daemon will
    // rewrite it on every revocation change.
    actions.push(ensureKrl(ca));

    // Wrapper script
    actions.push(writeIfChanged(WRAPPER_PATH, wrapperContent(installDir), 0o755));

    // sshd snippet (from repo) and unit (from repo)
    const snippetAction = writeIfChanged(SSHD_SNIPPET_PATH, readSnippet(installDir), 0o644);
    actions.push(snippetAction);

    const unitAction = writeIfChanged(SYSTEMD_UNIT_PATH, readUnit(installDir), 0o644);
    actions.push(unitAction);

    for (const a of actions) process.stdout.write(`  ${a.changed ? "✦" : "·"} ${a.note}\n`);

    // Reload sshd if its config changed (gracefully — reload doesn't drop existing sessions)
    if (snippetAction.changed) {
        process.stdout.write("\nreloading sshd...\n");
        systemctlReload("ssh");
    }

    // Install/enable daemon. Always daemon-reload + enable; only restart if unit changed or not active.
    if (unitAction.changed || !isActive("mad-daemon")) {
        process.stdout.write("\nenabling mad-daemon...\n");
        systemctlEnableNow("mad-daemon");
    } else {
        process.stdout.write("\nmad-daemon already active.\n");
    }

    process.stdout.write("\nsetup complete.\n");
}
