name: Release Client Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/mad-linux
