name: Release Client Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: oven-sh/setup-bun@v2
      - run: npm ci
      - run: npm run build:client
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/mad-linux
